# coding: utf-8

"""
    API for AuthApplication

    Bran's Auth API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authclient.api.signout_api import SignoutApi  # noqa: E501


class TestSignoutApi(unittest.TestCase):
    """SignoutApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SignoutApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_signout(self) -> None:
        """Test case for signout

        """
        pass


if __name__ == '__main__':
    unittest.main()
