# coding: utf-8

"""
    API for AuthApplication

    Bran's Auth API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from authclient.models.permission import Permission  # noqa: E501

class TestPermission(unittest.TestCase):
    """Permission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Permission:
        """Test Permission
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Permission`
        """
        model = Permission()  # noqa: E501
        if include_optional:
            return Permission(
                id = '',
                name = '',
                roles = [
                    authclient.models.role.Role(
                        id = '', 
                        name = '', 
                        permissions = [
                            authclient.models.permission.Permission(
                                id = '', 
                                name = '', 
                                roles = [
                                    authclient.models.role.Role(
                                        id = '', 
                                        name = '', 
                                        authority = '', )
                                    ], 
                                authority = '', )
                            ], 
                        authority = '', )
                    ],
                authority = ''
            )
        else:
            return Permission(
        )
        """

    def testPermission(self):
        """Test Permission"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
