# coding: utf-8

"""
    API for AuthApplication

    Bran's Auth API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authclient.api.validate_email_verification_api import ValidateEmailVerificationApi  # noqa: E501


class TestValidateEmailVerificationApi(unittest.TestCase):
    """ValidateEmailVerificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ValidateEmailVerificationApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_validate_email_verification(self) -> None:
        """Test case for validate_email_verification

        """
        pass


if __name__ == '__main__':
    unittest.main()
