# coding: utf-8

"""
    API for AuthApplication

    Bran's Auth API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authclient.api.update_user_details_api import UpdateUserDetailsApi  # noqa: E501


class TestUpdateUserDetailsApi(unittest.TestCase):
    """UpdateUserDetailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UpdateUserDetailsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_update_user_details(self) -> None:
        """Test case for update_user_details

        """
        pass


if __name__ == '__main__':
    unittest.main()
