# coding: utf-8

"""
    API for AuthApplication

    Bran's Auth API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authclient.api.send_custom_email_verification_api import SendCustomEmailVerificationApi  # noqa: E501


class TestSendCustomEmailVerificationApi(unittest.TestCase):
    """SendCustomEmailVerificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SendCustomEmailVerificationApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_post_method_name(self) -> None:
        """Test case for post_method_name

        """
        pass


if __name__ == '__main__':
    unittest.main()
