/*
 * API for AuthApplication
 *
 * Bran's Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthResponse {
    #[serde(rename = "errored", skip_serializing_if = "Option::is_none")]
    pub errored: Option<bool>,
    #[serde(rename = "messages", skip_serializing_if = "Option::is_none")]
    pub messages: Option<Vec<String>>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "refreshToken", skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
    #[serde(rename = "userDetails", skip_serializing_if = "Option::is_none")]
    pub user_details: Option<Box<crate::models::ResponseUserDetails>>,
}

impl AuthResponse {
    pub fn new() -> AuthResponse {
        AuthResponse {
            errored: None,
            messages: None,
            token: None,
            refresh_token: None,
            user_details: None,
        }
    }
}


