/*
 * API for AuthApplication
 *
 * Bran's Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserDetailsUpdateRequest {
    #[serde(rename = "otpId", skip_serializing_if = "Option::is_none")]
    pub otp_id: Option<String>,
    #[serde(rename = "otpCode", skip_serializing_if = "Option::is_none")]
    pub otp_code: Option<String>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl UserDetailsUpdateRequest {
    pub fn new() -> UserDetailsUpdateRequest {
        UserDetailsUpdateRequest {
            otp_id: None,
            otp_code: None,
            display_name: None,
            email: None,
            password: None,
        }
    }
}


