/* tslint:disable */
/* eslint-disable */
/**
 * API for AuthApplication
 * Bran\'s Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmailConfirmationOtpSubmitRequest
 */
export interface EmailConfirmationOtpSubmitRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailConfirmationOtpSubmitRequest
     */
    'otpId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailConfirmationOtpSubmitRequest
     */
    'code'?: string;
}

