/* tslint:disable */
/* eslint-disable */
/**
 * API for AuthApplication
 * Bran\'s Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ModelDate } from './model-date';

/**
 * 
 * @export
 * @interface OtpRequestResponse
 */
export interface OtpRequestResponse {
    /**
     * 
     * @type {boolean}
     * @memberof OtpRequestResponse
     */
    'errored'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof OtpRequestResponse
     */
    'messages'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OtpRequestResponse
     */
    'otpId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OtpRequestResponse
     */
    'email'?: string;
    /**
     * 
     * @type {ModelDate}
     * @memberof OtpRequestResponse
     */
    'expiryDate'?: ModelDate;
}

