/* tslint:disable */
/* eslint-disable */
/**
 * API for AuthApplication
 * Bran\'s Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Role } from './role';

/**
 * 
 * @export
 * @interface SigninResponse
 */
export interface SigninResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SigninResponse
     */
    'errored'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof SigninResponse
     */
    'messages'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SigninResponse
     */
    'token'?: string;
    /**
     * 
     * @type {string}
     * @memberof SigninResponse
     */
    'refreshToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof SigninResponse
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof SigninResponse
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SigninResponse
     */
    'email'?: string;
    /**
     * 
     * @type {Array<Role>}
     * @memberof SigninResponse
     */
    'roles'?: Array<Role>;
    /**
     * 
     * @type {boolean}
     * @memberof SigninResponse
     */
    'emailVerified'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SigninResponse
     */
    'lockedAccount'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SigninResponse
     */
    'deletedAccount'?: boolean;
}

