# coding: utf-8

"""
    API for AuthApplication

    Bran's Auth API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authclient.api.validate_email_verification_with_otp_api import ValidateEmailVerificationWithOtpApi  # noqa: E501


class TestValidateEmailVerificationWithOtpApi(unittest.TestCase):
    """ValidateEmailVerificationWithOtpApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ValidateEmailVerificationWithOtpApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_valilidate_email_verification_otp(self) -> None:
        """Test case for valilidate_email_verification_otp

        """
        pass


if __name__ == '__main__':
    unittest.main()
