# coding: utf-8

"""
    API for AuthApplication

    Bran's Auth API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from authclient.models.user_details_update_request import UserDetailsUpdateRequest  # noqa: E501

class TestUserDetailsUpdateRequest(unittest.TestCase):
    """UserDetailsUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserDetailsUpdateRequest:
        """Test UserDetailsUpdateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserDetailsUpdateRequest`
        """
        model = UserDetailsUpdateRequest()  # noqa: E501
        if include_optional:
            return UserDetailsUpdateRequest(
                otp_id = '',
                otp_code = '',
                display_name = '',
                email = '',
                password = ''
            )
        else:
            return UserDetailsUpdateRequest(
        )
        """

    def testUserDetailsUpdateRequest(self):
        """Test UserDetailsUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
