# coding: utf-8

"""
    API for AuthApplication

    Bran's Auth API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from authclient.models.model_date import ModelDate  # noqa: E501

class TestModelDate(unittest.TestCase):
    """ModelDate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelDate:
        """Test ModelDate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelDate`
        """
        model = ModelDate()  # noqa: E501
        if include_optional:
            return ModelDate(
                seconds = 56,
                time = 56,
                var_date = 56,
                month = 56,
                hours = 56,
                minutes = 56,
                year = 56,
                day = 56,
                timezone_offset = 56
            )
        else:
            return ModelDate(
        )
        """

    def testModelDate(self):
        """Test ModelDate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
