# coding: utf-8

"""
    API for AuthApplication

    Bran's Auth API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from authclient.models.otp_request import OtpRequest  # noqa: E501

class TestOtpRequest(unittest.TestCase):
    """OtpRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OtpRequest:
        """Test OtpRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OtpRequest`
        """
        model = OtpRequest()  # noqa: E501
        if include_optional:
            return OtpRequest(
                email_or_username = '',
                message = ''
            )
        else:
            return OtpRequest(
        )
        """

    def testOtpRequest(self):
        """Test OtpRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
