# coding: utf-8

"""
    API for AuthApplication

    Bran's Auth API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authclient.api.reset_user_password_api import ResetUserPasswordApi  # noqa: E501


class TestResetUserPasswordApi(unittest.TestCase):
    """ResetUserPasswordApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ResetUserPasswordApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_reset_user_password(self) -> None:
        """Test case for reset_user_password

        """
        pass


if __name__ == '__main__':
    unittest.main()
