/* tslint:disable */
/* eslint-disable */
/**
 * API for AuthApplication
 * Bran\'s Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../../../../../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../../../../../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../../../../../base';
// @ts-ignore
import { OtpRequest } from '../../../../../com/bran/auth/client/model';
// @ts-ignore
import { OtpRequestResponse } from '../../../../../com/bran/auth/client/model';
/**
 * SendCustomEmailVerificationApi - axios parameter creator
 * @export
 */
export const SendCustomEmailVerificationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {OtpRequest} otpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestOtp: async (otpRequest: OtpRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'otpRequest' is not null or undefined
            assertParamExists('requestOtp', 'otpRequest', otpRequest)
            const localVarPath = `/api/v1/auth/public/request-otp`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(otpRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SendCustomEmailVerificationApi - functional programming interface
 * @export
 */
export const SendCustomEmailVerificationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SendCustomEmailVerificationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {OtpRequest} otpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestOtp(otpRequest: OtpRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OtpRequestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestOtp(otpRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SendCustomEmailVerificationApi - factory interface
 * @export
 */
export const SendCustomEmailVerificationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SendCustomEmailVerificationApiFp(configuration)
    return {
        /**
         * 
         * @param {OtpRequest} otpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestOtp(otpRequest: OtpRequest, options?: any): AxiosPromise<OtpRequestResponse> {
            return localVarFp.requestOtp(otpRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SendCustomEmailVerificationApi - object-oriented interface
 * @export
 * @class SendCustomEmailVerificationApi
 * @extends {BaseAPI}
 */
export class SendCustomEmailVerificationApi extends BaseAPI {
    /**
     * 
     * @param {OtpRequest} otpRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SendCustomEmailVerificationApi
     */
    public requestOtp(otpRequest: OtpRequest, options?: AxiosRequestConfig) {
        return SendCustomEmailVerificationApiFp(this.configuration).requestOtp(otpRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

