/* tslint:disable */
/* eslint-disable */
/**
 * API for AuthApplication
 * Bran\'s Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../../../../../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../../../../../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../../../../../base';
// @ts-ignore
import { ApiResponse } from '../../../../../com/bran/auth/client/model';
// @ts-ignore
import { UserDetailsUpdateRequest } from '../../../../../com/bran/auth/client/model';
/**
 * UpdateUserDetailsApi - axios parameter creator
 * @export
 */
export const UpdateUserDetailsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {UserDetailsUpdateRequest} userDetailsUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserDetails: async (userDetailsUpdateRequest: UserDetailsUpdateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userDetailsUpdateRequest' is not null or undefined
            assertParamExists('updateUserDetails', 'userDetailsUpdateRequest', userDetailsUpdateRequest)
            const localVarPath = `/api/v1/auth/authenticated/update-user-details`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userDetailsUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UpdateUserDetailsApi - functional programming interface
 * @export
 */
export const UpdateUserDetailsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UpdateUserDetailsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {UserDetailsUpdateRequest} userDetailsUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUserDetails(userDetailsUpdateRequest: UserDetailsUpdateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUserDetails(userDetailsUpdateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UpdateUserDetailsApi - factory interface
 * @export
 */
export const UpdateUserDetailsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UpdateUserDetailsApiFp(configuration)
    return {
        /**
         * 
         * @param {UserDetailsUpdateRequest} userDetailsUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserDetails(userDetailsUpdateRequest: UserDetailsUpdateRequest, options?: any): AxiosPromise<ApiResponse> {
            return localVarFp.updateUserDetails(userDetailsUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UpdateUserDetailsApi - object-oriented interface
 * @export
 * @class UpdateUserDetailsApi
 * @extends {BaseAPI}
 */
export class UpdateUserDetailsApi extends BaseAPI {
    /**
     * 
     * @param {UserDetailsUpdateRequest} userDetailsUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UpdateUserDetailsApi
     */
    public updateUserDetails(userDetailsUpdateRequest: UserDetailsUpdateRequest, options?: AxiosRequestConfig) {
        return UpdateUserDetailsApiFp(this.configuration).updateUserDetails(userDetailsUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

