/* tslint:disable */
/* eslint-disable */
/**
 * API for AuthApplication
 * Bran\'s Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../../../../../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../../../../../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../../../../../base';
// @ts-ignore
import { AuthResponse } from '../../../../../com/bran/auth/client/model';
// @ts-ignore
import { EmailConfirmationOtpSubmitRequest } from '../../../../../com/bran/auth/client/model';
/**
 * ValidateEmailVerificationWithOtpApi - axios parameter creator
 * @export
 */
export const ValidateEmailVerificationWithOtpApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {EmailConfirmationOtpSubmitRequest} emailConfirmationOtpSubmitRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        valilidateEmailVerificationOtp: async (emailConfirmationOtpSubmitRequest: EmailConfirmationOtpSubmitRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'emailConfirmationOtpSubmitRequest' is not null or undefined
            assertParamExists('valilidateEmailVerificationOtp', 'emailConfirmationOtpSubmitRequest', emailConfirmationOtpSubmitRequest)
            const localVarPath = `/api/v1/auth/public/validate-email-verification-otp`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(emailConfirmationOtpSubmitRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ValidateEmailVerificationWithOtpApi - functional programming interface
 * @export
 */
export const ValidateEmailVerificationWithOtpApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ValidateEmailVerificationWithOtpApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {EmailConfirmationOtpSubmitRequest} emailConfirmationOtpSubmitRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async valilidateEmailVerificationOtp(emailConfirmationOtpSubmitRequest: EmailConfirmationOtpSubmitRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.valilidateEmailVerificationOtp(emailConfirmationOtpSubmitRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ValidateEmailVerificationWithOtpApi - factory interface
 * @export
 */
export const ValidateEmailVerificationWithOtpApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ValidateEmailVerificationWithOtpApiFp(configuration)
    return {
        /**
         * 
         * @param {EmailConfirmationOtpSubmitRequest} emailConfirmationOtpSubmitRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        valilidateEmailVerificationOtp(emailConfirmationOtpSubmitRequest: EmailConfirmationOtpSubmitRequest, options?: any): AxiosPromise<AuthResponse> {
            return localVarFp.valilidateEmailVerificationOtp(emailConfirmationOtpSubmitRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ValidateEmailVerificationWithOtpApi - object-oriented interface
 * @export
 * @class ValidateEmailVerificationWithOtpApi
 * @extends {BaseAPI}
 */
export class ValidateEmailVerificationWithOtpApi extends BaseAPI {
    /**
     * 
     * @param {EmailConfirmationOtpSubmitRequest} emailConfirmationOtpSubmitRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidateEmailVerificationWithOtpApi
     */
    public valilidateEmailVerificationOtp(emailConfirmationOtpSubmitRequest: EmailConfirmationOtpSubmitRequest, options?: AxiosRequestConfig) {
        return ValidateEmailVerificationWithOtpApiFp(this.configuration).valilidateEmailVerificationOtp(emailConfirmationOtpSubmitRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

