/*
 * API for AuthApplication
 *
 * Bran's Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailConfirmationOtpSubmitRequest {
    #[serde(rename = "otpId", skip_serializing_if = "Option::is_none")]
    pub otp_id: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

impl EmailConfirmationOtpSubmitRequest {
    pub fn new() -> EmailConfirmationOtpSubmitRequest {
        EmailConfirmationOtpSubmitRequest {
            otp_id: None,
            code: None,
        }
    }
}


