/*
 * API for AuthApplication
 *
 * Bran's Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OtpRequest {
    #[serde(rename = "emailOrUsername", skip_serializing_if = "Option::is_none")]
    pub email_or_username: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl OtpRequest {
    pub fn new() -> OtpRequest {
        OtpRequest {
            email_or_username: None,
            message: None,
        }
    }
}


