/*
 * API for AuthApplication
 *
 * Bran's Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OtpRequestResponse {
    #[serde(rename = "errored", skip_serializing_if = "Option::is_none")]
    pub errored: Option<bool>,
    #[serde(rename = "messages", skip_serializing_if = "Option::is_none")]
    pub messages: Option<Vec<String>>,
    #[serde(rename = "otpId", skip_serializing_if = "Option::is_none")]
    pub otp_id: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "expiryDate", skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<Box<crate::models::Date>>,
}

impl OtpRequestResponse {
    pub fn new() -> OtpRequestResponse {
        OtpRequestResponse {
            errored: None,
            messages: None,
            otp_id: None,
            email: None,
            expiry_date: None,
        }
    }
}


