/*
API for AuthApplication

Bran's Auth API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authclient

import (
	"encoding/json"
)

// checks if the TokenRefreshRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenRefreshRequest{}

// TokenRefreshRequest struct for TokenRefreshRequest
type TokenRefreshRequest struct {
	Token *string `json:"token,omitempty"`
}

// NewTokenRefreshRequest instantiates a new TokenRefreshRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenRefreshRequest() *TokenRefreshRequest {
	this := TokenRefreshRequest{}
	return &this
}

// NewTokenRefreshRequestWithDefaults instantiates a new TokenRefreshRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenRefreshRequestWithDefaults() *TokenRefreshRequest {
	this := TokenRefreshRequest{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *TokenRefreshRequest) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenRefreshRequest) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *TokenRefreshRequest) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *TokenRefreshRequest) SetToken(v string) {
	o.Token = &v
}

func (o TokenRefreshRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenRefreshRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableTokenRefreshRequest struct {
	value *TokenRefreshRequest
	isSet bool
}

func (v NullableTokenRefreshRequest) Get() *TokenRefreshRequest {
	return v.value
}

func (v *NullableTokenRefreshRequest) Set(val *TokenRefreshRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenRefreshRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenRefreshRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenRefreshRequest(val *TokenRefreshRequest) *NullableTokenRefreshRequest {
	return &NullableTokenRefreshRequest{value: val, isSet: true}
}

func (v NullableTokenRefreshRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenRefreshRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


