/* tslint:disable */
/* eslint-disable */
/**
 * API for AuthApplication
 * Bran\'s Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelDate
 */
export interface ModelDate {
    /**
     * 
     * @type {number}
     * @memberof ModelDate
     * @deprecated
     */
    'seconds'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelDate
     */
    'time'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelDate
     * @deprecated
     */
    'date'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelDate
     * @deprecated
     */
    'month'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelDate
     * @deprecated
     */
    'hours'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelDate
     * @deprecated
     */
    'minutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelDate
     * @deprecated
     */
    'year'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelDate
     * @deprecated
     */
    'day'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelDate
     * @deprecated
     */
    'timezoneOffset'?: number;
}

