/* tslint:disable */
/* eslint-disable */
/**
 * API for AuthApplication
 * Bran\'s Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignupRequest
 */
export interface SignupRequest {
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    'password'?: string;
}

