/*
 * API for AuthApplication
 * Bran's Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bran.auth.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for EmailConfirmationOtpSubmitRequest
 */
public class EmailConfirmationOtpSubmitRequestTest {
    private final EmailConfirmationOtpSubmitRequest model = new EmailConfirmationOtpSubmitRequest();

    /**
     * Model tests for EmailConfirmationOtpSubmitRequest
     */
    @Test
    public void testEmailConfirmationOtpSubmitRequest() {
        // TODO: test EmailConfirmationOtpSubmitRequest
    }

    /**
     * Test the property 'otpId'
     */
    @Test
    public void otpIdTest() {
        // TODO: test otpId
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

}
