/*
 * API for AuthApplication
 * Bran's Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bran.auth.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for UserDetailsUpdateRequest
 */
public class UserDetailsUpdateRequestTest {
    private final UserDetailsUpdateRequest model = new UserDetailsUpdateRequest();

    /**
     * Model tests for UserDetailsUpdateRequest
     */
    @Test
    public void testUserDetailsUpdateRequest() {
        // TODO: test UserDetailsUpdateRequest
    }

    /**
     * Test the property 'otpId'
     */
    @Test
    public void otpIdTest() {
        // TODO: test otpId
    }

    /**
     * Test the property 'otpCode'
     */
    @Test
    public void otpCodeTest() {
        // TODO: test otpCode
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

}
