/*
 * API for AuthApplication
 * Bran's Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bran.auth.client.model;

import com.bran.auth.client.model.Role;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for SigninResponse
 */
public class SigninResponseTest {
    private final SigninResponse model = new SigninResponse();

    /**
     * Model tests for SigninResponse
     */
    @Test
    public void testSigninResponse() {
        // TODO: test SigninResponse
    }

    /**
     * Test the property 'errored'
     */
    @Test
    public void erroredTest() {
        // TODO: test errored
    }

    /**
     * Test the property 'messages'
     */
    @Test
    public void messagesTest() {
        // TODO: test messages
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'refreshToken'
     */
    @Test
    public void refreshTokenTest() {
        // TODO: test refreshToken
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'roles'
     */
    @Test
    public void rolesTest() {
        // TODO: test roles
    }

    /**
     * Test the property 'emailVerified'
     */
    @Test
    public void emailVerifiedTest() {
        // TODO: test emailVerified
    }

    /**
     * Test the property 'lockedAccount'
     */
    @Test
    public void lockedAccountTest() {
        // TODO: test lockedAccount
    }

    /**
     * Test the property 'deletedAccount'
     */
    @Test
    public void deletedAccountTest() {
        // TODO: test deletedAccount
    }

}
